---
openapi: 3.0.2
info:
  title: open-management-portal
  version: 1.0.0
paths:
  /residencies:
    summary: Path used to manage the list of residencies.
    description: The REST endpoint/path used to list and create zero or more `residency`
      entities.  This path contains a `GET` and `POST` operation to perform the list
      and create tasks, respectively. When used to list all residencies, a truncated
      form of each residency called a "stub" is returned.
    get:
      responses:
        "200":
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/residency_stub'
          description: Successful response - returns an array of `residency_stub`
            entities.
      operationId: getresidencies
      summary: List All residencies in "stub" form
      description: Gets a list of all `residency_stub` entities.
    post:
      requestBody:
        description: A new `residency` to be created.
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/residency'
        required: true
      responses:
        "201":
          description: Successful response.
      operationId: createresidency
      summary: Create a residency
      description: Creates a new instance of a `residency`.
  /residencies/{residencyId}:
    summary: Path used to manage a single residency.
    description: The REST endpoint/path used to get, update, and delete single instances
      of an `residency`.  This path contains `GET`, `PUT`, and `DELETE` operations
      used to perform the get, update, and delete tasks, respectively.
    get:
      responses:
        "200":
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/residency'
          description: Successful response - returns a single `residency`.
      operationId: getresidency
      summary: Get a residency
      description: Gets the details of a single instance of a `residency`.
    put:
      requestBody:
        description: Updated `residency` information.
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/residency'
        required: true
      responses:
        "202":
          description: Successful response.
      operationId: updateresidency
      summary: Update a residency
      description: Updates an existing `residency`.
    delete:
      responses:
        "204":
          description: Successful response.
      operationId: deleteresidency
      summary: Delete a residency
      description: Deletes an existing `residency`.
    parameters:
      - name: residencyId
        description: A unique identifier for a `residency`.
        schema:
          type: string
        in: path
        required: true
components:
  schemas:
    residency:
      title: Root Type for residency
      description: ""
      type: object
      properties:
        id:
          format: int32
          type: integer
        customer_name:
          type: string
        project_name:
          type: string
        description:
          type: string
        location:
          type: string
        start_date:
          type: string
        end_date:
          type: string
        archive_date:
          type: string
        contacts:
          type: object
          properties:
            engagement_lead:
              type: object
              properties:
                name:
                  type: string
                email:
                  type: string
            technical_lead:
              type: object
              properties:
                name:
                  type: string
                email:
                  type: string
            customer_contact:
              type: object
              properties:
                name:
                  type: string
                email:
                  type: string
        openshift_cluster:
          type: object
          properties:
            cloud_provider:
              type: object
              properties:
                name:
                  type: string
                region:
                  type: string
            version:
              type: string
            sub_domain:
              type: string
            persistent_storage_size:
              type: string
            cluster_size:
              type: string
      example:
        id: 1
        customer_name: ""
        project_name: ""
        description: ""
        location: ""
        start_date: ""
        end_date: ""
        archive_date: ""
        contacts:
          engagement_lead:
            name: ""
            email: ""
          technical_lead:
            name: ""
            email: ""
          customer_contact:
            name: ""
            email: ""
        openshift_cluster:
          cloud_provider:
            name: OSP
            region: us-east-1
          version: v4.2
          sub_domain: ""
          persistent_storage_size: 50GB
          cluster_size: medium
    residency_stub:
      title: Root Type for residency_stub
      description: ""
      type: object
      properties:
        id:
          format: int32
          type: integer
        customer_name:
          type: string
        project_name:
          type: string
      example:
        id: 1
        customer_name: ""
        project_name: ""
